export const LOGIN_SETAUTH = 'LOGIN_SETAUTH';
export const LOGIN_UNSETAUTH = 'LOGIN_UNSETAUTH';

export const JOBLIST_START = 'JOBLIST_START';
export const JOBLIST_SUCCESS = 'JOBLIST_SUCCESS';
export const JOBLIST_FAIL = 'JOBLIST_FAIL';
export const JOBLIST_ALL = 'JOBLIST_ALL';
export const JOBLIST_DETAIL = 'JOBLIST_DETAIL';
export const JOBLIST_DETAILSUCCESS = 'JOBLIST_DETAILSUCCESS';
